language: cpp
sudo: required
dist: trusty
compiler: 
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake

script:
  mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . 